server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:D:\develop\h2\data\scala
    username: admin
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update  #每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
    database: h2